--- 
controls: 
- label: Github User
  name: github_user
  type: Textbox
- label: Github Token
  name: github_token
  type: Textbox
- label: User Name
  name: user_name
  type: Textbox
- label: User Email
  name: user_email
  type: Textbox
- label: Ssh Passphrase
  name: ssh_passphrase
  type: Textbox
