--- 
scripts: 
- file: github_credentials_setup
  description: GitHub Credentials Setup
- file: dotfiles_installation
  description: Dotfiles Installation
- file: ruby_environment
  description: Ruby Environment
- file: redis_installation
  description: Redis Installation
- file: resque_installation
  description: Resque Installation
- file: nginx_and_passenger
  description: Nginx and Passenger
- file: stackfu
  description: StackFu
